# set(STIXEL_WORLD_PATH "/home/nestor/Dropbox/KULeuven/projects/StixelWorld")
set(STIXEL_WORLD_PATH "/home/nestor/Dropbox/ros/hydro/nestormh/src/stixel_world")
set(DENSE_TRACKER_PATH "/home/nestor/Dropbox/projects/DenseTracker")
set(POLAR_CALIBRATION_PATH "/home/nestor/Dropbox/KULeuven/projects/PolarCalibration")
set(CUDALK_PATH "/home/nestor/Dropbox/ros/hydro/nestormh/src/stixel_world/cudaLK")
# set(CUDA_BIND_COMPILER --compiler-bindir "/home/nestor/Dropbox/ros/hydro/nestormh/src/stixel_world/compiler_bind")
set(POINT_MATCH_PATH "/home/nestor/Dropbox/ros/hydro/nestormh/src/stixel_world/PointMatch")
set(LIBELAS_PATH "/home/nestor/Dropbox/ros/hydro/nestormh/src/stixel_world/libs/libelas")